"""Ajouter compte_contrepartie et libelle_contrepartie

Revision ID: 3c1230aa6460
Revises: 745d64e719b2
Create Date: 2025-06-10 01:04:00.521279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1230aa6460'
down_revision = '745d64e719b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecritures_bancaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compte_contrepartie', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('libelle_contrepartie', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecritures_bancaires', schema=None) as batch_op:
        batch_op.drop_column('libelle_contrepartie')
        batch_op.drop_column('compte_contrepartie')

    # ### end Alembic commands ###
