"""Ajout de toutes les tables (users, societes, fec_files, ecritures_bancaires, regles_affectation)

Revision ID: 745d64e719b2
Revises: 22b626c6a9ac
Create Date: 2025-06-08 00:34:00.655959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745d64e719b2'
down_revision = '22b626c6a9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('date_debut_exercice', sa.Date(), nullable=True),
    sa.Column('date_fin_exercice', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin_org', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fec_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('nom_original', sa.String(length=255), nullable=False),
    sa.Column('taille_fichier', sa.BigInteger(), nullable=False),
    sa.Column('nb_lignes_total', sa.Integer(), nullable=False),
    sa.Column('nb_lignes_bancaires', sa.Integer(), nullable=False),
    sa.Column('date_import', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('encodage_detecte', sa.String(length=50), nullable=True),
    sa.Column('separateur_detecte', sa.String(length=5), nullable=True),
    sa.Column('societe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regles_affectation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('mots_cles', sa.JSON(), nullable=False),
    sa.Column('criteres_montant', sa.JSON(), nullable=True),
    sa.Column('journal_code', sa.String(length=10), nullable=True),
    sa.Column('compte_destination', sa.String(length=20), nullable=False),
    sa.Column('libelle_destination', sa.String(length=200), nullable=False),
    sa.Column('nb_transactions_couvertes', sa.Integer(), nullable=True),
    sa.Column('pourcentage_couverture_compte', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pourcentage_couverture_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('societe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecritures_bancaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_code', sa.String(length=10), nullable=False),
    sa.Column('journal_lib', sa.String(length=100), nullable=False),
    sa.Column('ecriture_num', sa.String(length=20), nullable=False),
    sa.Column('ecriture_date', sa.Date(), nullable=False),
    sa.Column('compte_num', sa.String(length=20), nullable=False),
    sa.Column('compte_lib', sa.String(length=200), nullable=False),
    sa.Column('comp_aux_num', sa.String(length=20), nullable=True),
    sa.Column('comp_aux_lib', sa.String(length=200), nullable=True),
    sa.Column('piece_ref', sa.String(length=30), nullable=True),
    sa.Column('piece_date', sa.Date(), nullable=True),
    sa.Column('ecriture_lib', sa.Text(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ecriture_let', sa.String(length=10), nullable=True),
    sa.Column('date_let', sa.Date(), nullable=True),
    sa.Column('valid_date', sa.Date(), nullable=True),
    sa.Column('montant_devise', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id_devise', sa.String(length=3), nullable=True),
    sa.Column('compte_final', sa.String(length=20), nullable=False),
    sa.Column('libelle_final', sa.String(length=200), nullable=False),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sens', sa.String(length=1), nullable=False),
    sa.Column('fec_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fec_file_id'], ['fec_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecritures_bancaires')
    op.drop_table('regles_affectation')
    op.drop_table('fec_files')
    op.drop_table('users')
    op.drop_table('societes')
    # ### end Alembic commands ###
